import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from '@/providers/ThemeProvider'
// import AuthProvider from '@/providers/AuthProvider'
// import Layout from "@/pages/layout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body suppressHydrationWarning={true} className={inter.className}>

                {/* <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >

                    <Layout>
                        {children}
                    </Layout>
                </ThemeProvider> */}
                <div className="flex flex-col  items-center justify-center mb-4 gap-20">
                    <div>
                        <h1 className="text-2xl font-bold">Figma Embed Example PTE demo 1</h1>
                        <p className="text-gray-600 mb-10">An example of embedding a Figma prototype in a Next.js app</p>
                        <iframe
                            style={{ border: "1px solid rgba(0,0,0,0.1)" }}
                            width={800}
                            height={450}
                            src="https://embed.figma.com/proto/J0P6FzueUgONICpMUdb0hG/demo-design-PTE?node-id=1-4&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&embed-host=share"
                            allow="clipboard-write"
                            allowFullScreen
                        />
                    </div>
                    <div>
                        <h1 className="text-2xl font-bold">Figma Embed PTE Example demo 2</h1>
                        <p className="text-gray-600 mb-10">An example of embedding a Figma prototype in a Next.js app</p>
                        <iframe
                            style={{ border: "1px solid rgba(0,0,0,0.1)" }}
                            width={800}
                            height={450}
                            src="https://embed.figma.com/proto/J0P6FzueUgONICpMUdb0hG/demo-design-PTE?node-id=9-2&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&embed-host=share"
                            allow="clipboard-write"
                            allowFullScreen

                        />

                    </div>

                </div>





            </body>
        </html>
    )
}
