import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import { categoriesServices } from "@/lib/service/category";
import ClientRoot from "@/components/shared/Layout/client-root";
import { CategoryProvider } from "@/context/category-context";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {

    const data = await categoriesServices.getCategoryTree({});

    const menu = Array.isArray(data) ? data : [];
    // console.log('navMenuData layout:', menu);

    return (
        <html lang="en" suppressHydrationWarning={true}>
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body suppressHydrationWarning={true} className={inter.className}>
                <CategoryProvider value={{category: data}}>
                    <ClientRoot navMenuData={menu}>
                        {children}
                    </ClientRoot>
                </CategoryProvider>
            </body>
        </html>
    )
}
